services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  backend:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/bayhan
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  bot:
    build: ./bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BACKEND_URL=http://backend:5000