version: "3.9"

services:
  # База Mongo
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  # API (Node.js backend)
  api:
    build: ./api
    restart: always
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - mongo

  # WebApp (React frontend)
  web:
    build: ./web
    restart: always
    ports:
      - "5173:80"
    env_file: .env
    depends_on:
      - api

  # Админ-бот
  admin-bot:
    build: ./admin-bot
    restart: always
    env_file: .env
    depends_on:
      - api