version: '3.8'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    ports:
      - "4000:4000"  # API
      - "4001:4001"  # Socket.io для real-time
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/bayhan
      - DATA_ENC_KEY=${DATA_ENC_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # Vite dev server
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app
volumes:
  mongo-data: